Existing GameBinder.cs hooks implemented
Terraria-Builders-Community/Starlight pull request #7
Opened 2022-11-28 21:32 UTC by RenderBr

2022-11-28 21:34 UTC, Rozen4334 commented on src/Starlight.Server/Hooks/HookCaller.cs
> +                    break;
```suggestion
                    return handle;
```

2022-11-28 21:35 UTC, Rozen4334 commented on src/Starlight.Server/Hooks/HookCaller.cs
> +        public async Task InvokeGameUpdateAsync()
```suggestion
        public async Task OnGameUpdateAsync()
```

Inconsistent naming. Why are we adding `Invoke` here?

2022-11-28 21:35 UTC, Rozen4334 commented on src/Starlight.Server/Hooks/HookCaller.cs
> +                    await InvokeGameWorldDisconnect();
```suggestion
                    await OnGameWorldDisconnect();
```

2022-11-28 21:35 UTC, Rozen4334 commented on src/Starlight.Server/Hooks/HookCaller.cs
> +                    await InvokeGameWorldConnect();
```suggestion
                    await OnGameWorldConnect();
```

2022-11-28 21:35 UTC, Rozen4334 commented on src/Starlight.Server/Hooks/HookCaller.cs
> +                var handle = await resolver.InvokeGameUpdateAsync();
```suggestion
                var handle = await resolver.OnGameUpdateAsync();
```

2022-11-28 21:36 UTC, Rozen4334 commented on src/Starlight.Server/Hooks/HookCaller.cs
> +                var handle = await resolver.InvokePostGameUpdateAsync();
```suggestion
                var handle = await resolver.OnPostGameUpdateAsync();
```

2022-11-28 21:36 UTC, Rozen4334 commented on src/Starlight.Server/Hooks/HookCaller.cs
> +        public async Task InvokePostGameUpdateAsync()
```suggestion
        public async Task OnPostGameUpdateAsync()
```

2022-11-28 21:37 UTC, Rozen4334 commented on src/Starlight.Server/Hooks/HookCaller.cs
> +using System.Reflection.Metadata.Ecma335;
```suggestion
```

accident?

2022-11-28 21:37 UTC, Rozen4334 commented on src/Starlight.Server/Hooks/HookCaller.cs
> +using IL.Terraria;
```suggestion
using Terraria;
```

2022-11-28 21:37 UTC, Rozen4334 commented on src/Starlight.Server/Hooks/HookCaller.cs
> +using MongoDB.Driver;
```suggestion
```

2022-11-28 21:37 UTC, Rozen4334 commented on src/Starlight.Server/Hooks/Binders/Implementations/GameBinder.cs
> +            _ = _caller.InvokePostGameUpdateAsync();
```suggestion
            _ = _caller.OnPostGameUpdateAsync();
```

2022-11-28 21:37 UTC, Rozen4334 commented on src/Starlight.Server/Hooks/Binders/Implementations/GameBinder.cs
> +             _ = _caller.InvokeGameUpdateAsync();
```suggestion
             _ = _caller.OnGameUpdateAsync();
```

2022-11-28 21:38 UTC, Rozen4334 commented on src/Starlight.Server/Hooks/HookResolver.cs
> +        public virtual Task<HandleResult> InvokePostGameUpdateAsync()
```suggestion
        public virtual Task<HandleResult> OnPostGameUpdateAsync()
```

2022-11-28 21:38 UTC, Rozen4334 commented on src/Starlight.Server/Hooks/HookResolver.cs
> +        public virtual Task<HandleResult> InvokeGameUpdateAsync()
```suggestion
        public virtual Task<HandleResult> OnGameUpdateAsync()
```

2022-11-28 21:46 UTC, Rozen4334 approved these changes
lgtm

2022-11-28 23:38 UTC, Rozen4334 requested changes
Why is it invoke again grrr

2022-11-28 23:43 UTC, RenderBr commented
> Why is it invoke again grrr

fixed. sorry babe dont growl at me god

2022-11-28 23:43 UTC, RenderBr commented
> Why is it invoke again grrr

why do you do this every time 😢

2022-11-29 10:33 UTC, merged

2022-11-29 10:33 UTC, Rozen4334 commented
Force merging as naming is inappropriate and I want to continue on hooks branch